# Generated by Django 2.2.1 on 2019-07-01 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'work categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='worktracker.Client')),
            ],
            options={
                'ordering': ['client__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True, db_index=True)),
                ('end', models.DateField(db_index=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='worktracker.WorkCategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='worktracker.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
